name: Subir Excels a Drive

on:
  push:
    paths:
      - 'excels/*.xlsm'
  workflow_dispatch:
    inputs:
      carpeta_drive:
        description: 'Subcarpeta opcional dentro del remote (dejar vacío para raíz)'
        required: false
        default: ''
      sobrescribir:
        description: 'Sobrescribir archivos si ya existen'
        required: false
        type: boolean
        default: true

jobs:
  subir-a-drive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Instalar Rclone
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone

    - name: Configurar Rclone
      env:
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      run: |
        mkdir -p ~/.config/rclone
        echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf

    - name: Subir Excels a Drive
      env:
        DESTINO: ${{ inputs.carpeta_drive }}
        SOBRESCRIBIR: ${{ inputs.sobrescribir }}
      run: |
        DESTINO_FINAL="utn-frc-planes-estudio-sync:${DESTINO:-}"
        OPCIONES=""
        if [ "$SOBRESCRIBIR" != "true" ]; then
          OPCIONES="--ignore-existing"
        fi
        echo "Subiendo archivos a $DESTINO_FINAL con opciones: $OPCIONES"
        rclone copy "excels/" "$DESTINO_FINAL" --progress --include "*.xlsm" $OPCIONES
